### ISSUE TITLE
Error while importing to database

### ISSUE THREAD

**Issue by nextstopsun** [danieluct/pypgroutingloader#1]
Two issues here:
1. There is a bug in dbwriter.py:
   Line 121 
   `cursor.execute('CREATE UNIQUE INDEX IF NOT EXISTS {0}ways_gid_idx ON ways USING btree(gid);'.format(self.table_prefix))`
   Should really be a:
   `cursor.execute('CREATE UNIQUE INDEX IF NOT EXISTS {0}ways_gid_idx ON {0}ways USING btree(gid);'.format(self.table_prefix))`
2. Wanted to make a pull request for the first one, but got another one, which isn't so trivial:

```
Traceback (most recent call last):
  File "pgroutingloader.py", line 574, in <module>
    table_prefix=args.prefix)
  File "pgroutingloader.py", line 416, in run
    db_writer.insert_way(segment, node_processor.get_node_coordinates())
  File "/work/pypgroutingloader/src/util/dbwriter.py", line 247, in insert_way
    TextGeometry(segment.get_wkt(nodes))
  File "/work/pypgroutingloader/src/OSMEntities/Objects.py", line 415, in get_wkt
    pair_as_string(nodes.get(self._tail)) + ")") 
  File "/work/pypgroutingloader/src/util/tag_utils.py", line 42, in pair_as_string
    return ' '.join([str(x) for x in pair])
TypeError: 'NoneType' object is not iterable
```

Any clues?

**Comment by danieluct** [comment]
Good catch on the first one. Regarding the second, could you provide me with more info about the input format (pbf, xml, was pyosm.importer installed in the system/virtualenv used to import) ? I hope I will be able to look into the issue in the following days.

**Comment by nextstopsun** [comment]
I'm importing from osm xml without imposm.parser The error doesn't fire up right at the beginning, but after nodes get loaded to the database. I'm loading with: 
`python2 pgroutingloader.py --file extr.osm --connection-string "dbname='routedb' host='localhost' port='5432' user='me' password='mypass'" --prefix-tables "osm_" --lenght-projection 32636`

BTW `--lenght-projection` is a typo, should really be `--length-projection`:)

First the importer gives me a bunch of warnings about unknown barrier tag values, then deleted barrier restrictions on unroutable ways, the last message is `INFO     nodes loaded` which looks good. After a couple of seconds the error comes up. I guess something gets broken in `nodes.get(self._tail)` part.

**Comment by danieluct** [comment]
Hey, thanks for the info (and for spotting the typo). I'm however unable to reproduce the error. Is there any way you could provide me with the input file you used?

**Comment by nextstopsun** [comment]
Sure, I'm trying to import [this file](https://yadi.sk/d/73hG04uouxAaE)
And I also get `UserWarning: imposm.parser library not found. Will use XML parser` - so I'm not using imposm. Thanks for helping out here:)

**Comment by danieluct** [comment]
It seems there's a problem with the input file: for some reason, several nodes of route [230600866](http://www.openstreetmap.org/way/230600866) are not exported in the xml format. I've modified the code so that such problems, though logged with error level, do not break the whole process (of course, the segments including node refs without corresponding node tags will not be routable)/
